modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "LGPL-2.1"

[[mods]]
modId = "im_struggling_with_my_inventory"
version = "${version}"
displayName = "I'm Struggling With My Inventory!!"
authors = "Katatsumuri.pan"
description = '''
This is a KUSO mod!!!
'''
#logoFile = ""

[[dependencies.im_struggling_with_my_inventory]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.im_struggling_with_my_inventory]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.im_struggling_with_my_inventory]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
